version: '3.3'
services:
  db:
    image: mysql:8.0.39
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=databaseword
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=ADMIN123

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wordpress
      - WORDPRESS_DB_USER=databaseword
      - WORDPRESS_DB_PASSWORD=admin
      - WORDPRESS_DB_NAME=ADMIN123

volumes:
  db_data:
